# Generated by Django 5.1.2 on 2025-09-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
